spring:
  application:
    name: flixy

  datasource:
    url: jdbc:postgresql://localhost:5432/flixy
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true

springdoc:
  api-docs:
    path: /api/api-docs
  swagger-ui:
    path: /swagger/index.html

flixy:
  security:
    secret: "secret-word"
